export const PUBLISH_TO_PUBLIC = 'PUBLISH_TO_PUBLIC'
export const PUBLISH_TO_PEERS = 'PUBLISH_TO_PEERS'
export const UPDATE_PORTFOLIO_PRIVACY = 'UPDATE_PORTFOLIO_PRIVACY'
export const UPDATE_PORTFOLIO_PRIVACY_SUCCESS =
  'UPDATE_PORTFOLIO_PRIVACY_SUCCESS'
export const UPDATE_PORTFOLIO_PRIVACY_ERROR = 'UPDATE_PORTFOLIO_PRIVACY_ERROR'

// modals
export const SET_VISIBILITY_MODAL = 'SET_VISIBILITY_MODAL'
export const SET_VISIBILITY_MODAL_SUCCESS = 'SET_VISIBILITY_MODAL_SUCCESS'
export const SET_VISIBILITY_MODAL_ERROR = 'SET_VISIBILITY_MODAL_ERROR'
export const SET_PUBLISH_MODAL = 'SET_PUBLISH_MODAL'
export const SET_PUBLISH_MODAL_SUCCESS = 'SET_PUBLISH_MODAL_SUCCESS'
export const SET_PUBLISH_MODAL_ERROR = 'SET_PUBLISH_MODAL_ERROR'

export const SET_VISIBILITY_MODAL_CONTENT = 'SET_VISIBILITY_MODAL_CONTENT'
export const SET_VISIBILITY_MODAL_CONTENT_SUCCESS =
  'SET_VISIBILITY_MODAL_CONTENT_SUCCESS'
export const SET_VISIBILITY_MODAL_CONTENT_ERROR =
  'SET_VISIBILITY_MODAL_CONTENT_ERROR'

export const SET_SHARE_MODAL = 'SET_SHARE_MODAL'
export const SET_SHARE_MODAL_SUCCESS = 'SET_SHARE_MODAL_SUCCESS'
export const SET_SHARE_MODAL_ERROR = 'SET_SHARE_MODAL_ERROR'

export const SHOW_EDIT_MENTOR_MODAL = 'SHOW_EDIT_MENTOR_MODAL'
export const HIDE_EDIT_MENTOR_MODAL = 'HIDE_EDIT_MENTOR_MODAL'

export const SHOW_ADD_MENTOR_MODAL = 'SHOW_ADD_MENTOR_MODAL'
export const HIDE_ADD_MENTOR_MODAL = 'HIDE_ADD_MENTOR_MODAL'

export const SHOW_EDIT_FAILURE_MODAL = 'SHOW_EDIT_FAILURE_MODAL'
export const HIDE_EDIT_FAILURE_MODAL = 'HIDE_EDIT_FAILURE_MODAL'

export const SHOW_ADD_FAILURE_MODAL = 'SHOW_ADD_FAILURE_MODAL'
export const HIDE_ADD_FAILURE_MODAL = 'HIDE_ADD_FAILURE_MODAL'

export const SET_SHARE_MODAL_CONTENT = 'SET_SHARE_MODAL_CONTENT'
export const SET_SHARE_MODAL_CONTENT_SUCCESS = 'SET_SHARE_MODAL_CONTENT_SUCCESS'
export const SET_SHARE_MODAL_CONTENT_ERROR = 'SET_SHARE_MODAL_CONTENT_ERROR'

export const GET_PORTFOLIO_PRIVACY = 'GET_PORTFOLIO_PRIVACY'
export const GET_PORTFOLIO_PRIVACY_SUCCESS = 'GET_PORTFOLIO_PRIVACY_SUCCESS'
export const GET_PORTFOLIO_PRIVACY_ERROR = 'GET_PORTFOLIO_PRIVACY_ERROR'
export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE'
export const CHANGE_VIEW_MODE_SUCCESS = 'CHANGE_VIEW_MODE_SUCCESS'
export const CHANGE_VIEW_MODE_ERROR = 'CHANGE_VIEW_MODE_ERROR'

export const CHANGE_ACTIVE_SECTION = 'CHANGE_ACTIVE_SECTION'
export const CHANGE_ACTIVE_SECTION_SUCCESS = 'CHANGE_ACTIVE_SECTION_SUCCESS'
export const CHANGE_ACTIVE_SECTION_ERROR = 'CHANGE_ACTIVE_SECTION_ERROR'

export const PUBLISH_PORTFOLIO_SECTION = 'PUBLISH_PORTFOLIO_SECTION'
export const PUBLISH_PORTFOLIO_SECTION_SUCCESS =
  'PUBLISH_PORTFOLIO_SECTION_SUCCESS'
export const PUBLISH_PORTFOLIO_SECTION_ERROR = 'PUBLISH_PORTFOLIO_SECTION_ERROR'

export const SHARE_PORTFOLIO_SECTION = 'SHARE_PORTFOLIO_SECTION'
export const SHARE_PORTFOLIO_SECTION_SUCCESS = 'SHARE_PORTFOLIO_SECTION_SUCCESS'
export const SHARE_PORTFOLIO_SECTION_ERROR = 'SHARE_PORTFOLIO_SECTION_ERROR'

// Constants for isEditMyRelationship
export const EDIT_MY_RELATIONSHIP = 'EDIT_MY_RELATIONSHIP'
export const EDIT_MY_RELATIONSHIP_SUCCESS = 'EDIT_MY_RELATIONSHIP_SUCCESS'
export const EDIT_MY_RELATIONSHIP_ERROR = 'EDIT_MY_RELATIONSHIP_ERROR'

// Constants for isEditMyFailures
export const EDIT_MY_FAILURES = 'EDIT_MY_FAILURES'
export const EDIT_MY_FAILURES_SUCCESS = 'EDIT_MY_FAILURES_SUCCESS'
export const EDIT_MY_FAILURES_ERROR = 'EDIT_MY_FAILURES_ERROR'

// Constants for isEditMyMentors
export const EDIT_MY_MENTORS = 'EDIT_MY_MENTORS'
export const EDIT_MY_MENTORS_SUCCESS = 'EDIT_MY_MENTORS_SUCCESS'
export const EDIT_MY_MENTORS_ERROR = 'EDIT_MY_MENTORS_ERROR'
export const EDIT_WHO_SECTION = 'EDIT_WHO_SECTION'
export const EDIT_WHO_SECTION_SUCCESS = 'EDIT_WHO_SECTION_SUCCESS'
export const EDIT_WHO_SECTION_ERROR = 'EDIT_WHO_SECTION_ERROR'

export const SAVE_WHO_SECTION = 'SAVE_WHO_SECTION'
export const SAVE_WHO_SECTION_SUCCESS = 'SAVE_WHO_SECTION_SUCCESS'
export const SAVE_WHO_SECTION_ERROR = 'SAVE_WHO_SECTION_ERROR'

export const SAVE_PERSONAL_BRAND_STORY = 'SAVE_PERSONAL_BRAND_STORY'
export const SAVE_PERSONAL_BRAND_STORY_SUCCESS =
  'SAVE_PERSONAL_BRAND_STORY_SUCCESS'
export const SAVE_PERSONAL_BRAND_STORY_ERROR = 'SAVE_PERSONAL_BRAND_STORY_ERROR'

export const GET_USER_STORY = 'GET_USER_STORY'
export const GET_USER_STORY_SUCCESS = 'GET_USER_STORY_SUCCESS'
export const GET_USER_STORY_ERROR = 'GET_USER_STORY_ERROR'

export const SAVE_USER_STORY = 'SAVE_USER_STORY'
export const SAVE_USER_STORY_SUCCESS = 'SAVE_USER_STORY_SUCCESS'
export const SAVE_USER_STORY_ERROR = 'SAVE_USER_STORY_ERROR'

export const GET_MY_RELATIONSHIPS = 'GET_MY_RELATIONSHIPS'
export const GET_MY_RELATIONSHIPS_SUCCESS = 'GET_MY_RELATIONSHIPS_SUCCESS'
export const GET_MY_RELATIONSHIPS_ERROR = 'GET_MY_RELATIONSHIPS_ERROR'

export const SAVE_MY_RELATIONSHIPS = 'SAVE_MY_RELATIONSHIPS'
export const SAVE_MY_RELATIONSHIPS_SUCCESS = 'SAVE_MY_RELATIONSHIPS_SUCCESS'
export const SAVE_MY_RELATIONSHIPS_ERROR = 'SAVE_MY_RELATIONSHIPS_ERROR'

export const GET_MY_FAILURES = 'GET_MY_FAILURES'
export const GET_MY_FAILURES_SUCCESS = 'GET_MY_FAILURES_SUCCESS'
export const GET_MY_FAILURES_ERROR = 'GET_MY_FAILURES_ERROR'

export const SAVE_MY_FAILURES = 'SAVE_MY_FAILURES'
export const SAVE_MY_FAILURES_SUCCESS = 'SAVE_MY_FAILURES_SUCCESS'
export const SAVE_MY_FAILURES_ERROR = 'SAVE_MY_FAILURES_ERROR'
export const CREATE_MY_FAILURE = 'CREATE_MY_FAILURE'
export const CREATE_MY_FAILURE_SUCCESS = 'CREATE_MY_FAILURE_SUCCESS'
export const CREATE_MY_FAILURE_ERROR = 'CREATE_MY_FAILURE_ERROR'

export const UPDATE_MY_FAILURE = 'UPDATE_MY_FAILURE'
export const UPDATE_MY_FAILURE_SUCCESS = 'UPDATE_MY_FAILURE_SUCCESS'
export const UPDATE_MY_FAILURE_ERROR = 'UPDATE_MY_FAILURE_ERROR'

export const DELETE_MY_FAILURE = 'DELETE_MY_FAILURE'
export const DELETE_MY_FAILURE_SUCCESS = 'DELETE_MY_FAILURE_SUCCESS'
export const DELETE_MY_FAILURE_ERROR = 'DELETE_MY_FAILURE_ERROR'

export const DELETE_MY_FAILURE_IMAGE = 'DELETE_MY_FAILURE_IMAGE'
export const DELETE_MY_FAILURE_IMAGE_SUCCESS = 'DELETE_MY_FAILURE_IMAGE_SUCCESS'
export const DELETE_MY_FAILURE_IMAGE_ERROR = 'DELETE_MY_FAILURE_IMAGE_ERROR'

// MY MENTORS
export const GET_MY_MENTORS = 'GET_MY_MENTORS'
export const GET_MY_MENTORS_SUCCESS = 'GET_MY_MENTORS_SUCCESS'
export const GET_MY_MENTORS_ERROR = 'GET_MY_MENTORS_ERROR'

export const SAVE_MY_MENTORS = 'SAVE_MY_MENTORS'
export const SAVE_MY_MENTORS_SUCCESS = 'SAVE_MY_MENTORS_SUCCESS'
export const SAVE_MY_MENTORS_ERROR = 'SAVE_MY_MENTORS_ERROR'

export const CREATE_MY_MENTOR = 'CREATE_MY_MENTOR'
export const CREATE_MY_MENTOR_SUCCESS = 'CREATE_MY_MENTOR_SUCCESS'
export const CREATE_MY_MENTOR_ERROR = 'CREATE_MY_MENTOR_ERROR'

export const UPDATE_MY_MENTOR = 'UPDATE_MY_MENTOR'
export const UPDATE_MY_MENTOR_SUCCESS = 'UPDATE_MY_MENTOR_SUCCESS'
export const UPDATE_MY_MENTOR_ERROR = 'UPDATE_MY_MENTOR_ERROR'

export const DELETE_MY_MENTOR_IMAGE = 'DELETE_MY_MENTOR_IMAGE'
export const DELETE_MY_MENTOR_IMAGE_SUCCESS = 'DELETE_MY_MENTOR_IMAGE_SUCCESS'
export const DELETE_MY_MENTOR_IMAGE_ERROR = 'DELETE_MY_MENTOR_IMAGE_ERROR'

export const DELETE_MY_MENTOR = 'DELETE_MY_MENTOR'
export const DELETE_MY_MENTOR_SUCCESS = 'DELETE_MY_MENTOR_SUCCESS'
export const DELETE_MY_MENTOR_ERROR = 'DELETE_MY_MENTOR_ERROR'
