// GENERAL
export const CHANGE_SIDEBAR_STATE = 'CHANGE_SIDEBAR_STATE'
export const SET_ACCORDION_TOGGLED = 'SET_ACCORDION_TOGGLED'
export const SET_IMAGE_CROPPER_DATA = 'SET_IMAGE_CROPPER_DATA'
export const SET_CROPPED_IMAGE = 'SET_CROPPED_IMAGE'
