// GET Podcast
export const GET_ALL_PODCAST = 'GET_ALL_PODCAST'
export const GET_ALL_PODCAST_ERROR = 'GET_ALL_PODCAST_ERROR'
export const GET_GUIDANCE_VIDEOS = 'GET_GUIDANCE_VIDEOS'
export const GET_MASTERCLASS_VIDEOS = 'GET_MASTERCLASS_VIDEOS'
export const SET_LOADING = 'SET_LOADING'
