export const FETCH_CHALLENGE_PROGRESS_START = 'FETCH_CHALLENGE_PROGRESS_START'
export const FETCH_CHALLENGE_PROGRESS_SUCCESS = 'FETCH_CHALLENGE_PROGRESS_SUCCESS'
export const FETCH_CHALLENGE_PROGRESS_ERROR = 'FETCH_CHALLENGE_PROGRESS_ERROR'
export const CLEAR_CHALLENGE_PROGRESS = 'CLEAR_CHALLENGE_PROGRESS'
