export const GET_ALL_USERS_PENDING = 'GET_ALL_USERS_PENDING'
export const GET_ALL_USERS_FULFILLED = 'GET_ALL_USERS_FULFILLED'
export const GET_ALL_USERS_REJECTED = 'GET_ALL_USERS_REJECTED'
export const GET_USER_WITH_ID_PENDING = 'GET_USER_WITH_ID_PENDING'
export const GET_USER_WITH_ID_FULFILLED = 'GET_USER_WITH_ID_FULFILLED'
export const GET_USER_WITH_ID_REJECTED = 'GET_USER_WITH_ID_REJECTED'

export const GET_STUDENT_INFO_BY_ID = 'GET_BASIC_USER_INFO_BY_ID'
export const GET_STUDENT_INFO_BY_ID_SUCCESS =
  'GET_BASIC_USER_INFO_BY_ID_SUCCESS'
export const GET_STUDENT_INFO_BY_ID_ERROR = 'GET_BASIC_USER_INFO_BY_ID_ERROR'

export const EDIT_USER_WITH_ID_PENDING = 'EDIT_USER_WITH_ID_PENDING'
export const EDIT_USER_WITH_ID_FULFILLED = 'EDIT_USER_WITH_ID_FULFILLED'
export const EDIT_USER_WITH_ID_REJECTED = 'EDIT_USER_WITH_ID_REJECTED'
