// Metrics
export const FETCH_METRICS_PENDING = 'FETCH_METRICS_PENDING'
export const FETCH_METRICS_FULFILLED = 'FETCH_METRICS_FULFILLED'
export const FETCH_METRICS_REJECTED = 'FETCH_METRICS_REJECTED'

// Level Statistics
export const FETCH_LEVEL_STATS_PENDING = 'FETCH_LEVEL_STATS_PENDING'
export const FETCH_LEVEL_STATS_FULFILLED = 'FETCH_LEVEL_STATS_FULFILLED'
export const FETCH_LEVEL_STATS_REJECTED = 'FETCH_LEVEL_STATS_REJECTED'

// Demographics
export const FETCH_DEMOGRAPHICS_PENDING = 'FETCH_DEMOGRAPHICS_PENDING'
export const FETCH_DEMOGRAPHICS_FULFILLED = 'FETCH_DEMOGRAPHICS_FULFILLED'
export const FETCH_DEMOGRAPHICS_REJECTED = 'FETCH_DEMOGRAPHICS_REJECTED'

// User Status
export const FETCH_USER_STATUS_PENDING = 'FETCH_USER_STATUS_PENDING'
export const FETCH_USER_STATUS_FULFILLED = 'FETCH_USER_STATUS_FULFILLED'
export const FETCH_USER_STATUS_REJECTED = 'FETCH_USER_STATUS_REJECTED'

// Analytics
export const FETCH_ANALYTICS_PENDING = 'FETCH_ANALYTICS_PENDING'
export const FETCH_ANALYTICS_FULFILLED = 'FETCH_ANALYTICS_FULFILLED'
export const FETCH_ANALYTICS_REJECTED = 'FETCH_ANALYTICS_REJECTED'

// Revenue Analytics
export const FETCH_REVENUE_ANALYTICS_PENDING = 'FETCH_REVENUE_ANALYTICS_PENDING'
export const FETCH_REVENUE_ANALYTICS_FULFILLED = 'FETCH_REVENUE_ANALYTICS_FULFILLED'
export const FETCH_REVENUE_ANALYTICS_REJECTED = 'FETCH_REVENUE_ANALYTICS_REJECTED'

// Clear Cache
export const CLEAR_ADMIN_DASHBOARD_CACHE = 'CLEAR_ADMIN_DASHBOARD_CACHE'